import type { MarketProbability, NormalizedMarket, OrderBook } from "@dollarcast/shared";

export const fixtureMarkets: NormalizedMarket[] = [
  {
    marketTicker: "KXHIGHNY-26JUN25-B75",
    eventTicker: "KXHIGHNY-26JUN25",
    seriesTicker: "KXHIGHNY",
    rawTitle: "Will the high temperature in New York, NY be above 75F on Jun 25, 2026?",
    rawSubtitle: "New York daily high temperature",
    yesSubtitle: "Above 75F",
    noSubtitle: "75F or below",
    marketType: "daily_temperature",
    direction: "high",
    cityName: "New York",
    stateCode: "NY",
    eventDateLocal: "2026-06-25",
    eventHourLocal: null,
    timezone: "America/New_York",
    rangeLowerF: 76,
    rangeUpperF: null,
    lowerInclusive: true,
    upperInclusive: false,
    stationId: "KNYC",
    stationName: "Central Park, NY",
    stationLatitude: 40.7794,
    stationLongitude: -73.9692,
    settlementSourceName: "National Weather Service station observation",
    settlementSourceUrl: "https://forecast.weather.gov/MapClick.php?lat=40.78&lon=-73.97",
    contractUrl: "https://kalshi.com/markets",
    contractTermsUrl: "https://kalshi.com/markets",
    closeTime: "2026-06-25T20:00:00Z",
    expirationTime: "2026-06-26T04:00:00Z",
    yesBid: 0.55,
    yesAsk: 0.58,
    noBid: 0.42,
    noAsk: 0.45,
    lastPrice: 0.56,
    volume: 4200,
    volume24h: 880,
    openInterest: 2300,
    liquidityDollars: 1600,
    fractionalTradingEnabled: true,
    rawRulesPrimary: "Market settles according to the official high temperature reported for the listed station.",
    rawRulesSecondary: "Temperature settlement source and observation window are defined by the contract terms.",
    parseStatus: "verified",
    parseWarnings: []
  },
  {
    marketTicker: "KXHIGHAUS-26JUN25-B100",
    eventTicker: "KXHIGHAUS-26JUN25",
    seriesTicker: "KXHIGHAUS",
    rawTitle: "Will the high temperature in Austin, TX be 100F or above on Jun 25, 2026?",
    rawSubtitle: "Austin daily high temperature",
    yesSubtitle: "100F or above",
    noSubtitle: "Below 100F",
    marketType: "daily_temperature",
    direction: "high",
    cityName: "Austin",
    stateCode: "TX",
    eventDateLocal: "2026-06-25",
    eventHourLocal: null,
    timezone: "America/Chicago",
    rangeLowerF: 100,
    rangeUpperF: null,
    lowerInclusive: true,
    upperInclusive: false,
    stationId: "KAUS",
    stationName: "Austin-Bergstrom International Airport",
    stationLatitude: 30.1945,
    stationLongitude: -97.6699,
    settlementSourceName: "National Weather Service station observation",
    settlementSourceUrl: "https://forecast.weather.gov/MapClick.php?lat=30.19&lon=-97.67",
    contractUrl: "https://kalshi.com/markets",
    contractTermsUrl: "https://kalshi.com/markets",
    closeTime: "2026-06-25T20:00:00Z",
    expirationTime: "2026-06-26T05:00:00Z",
    yesBid: 0.28,
    yesAsk: 0.31,
    noBid: 0.69,
    noAsk: 0.72,
    lastPrice: 0.3,
    volume: 3100,
    volume24h: 640,
    openInterest: 1900,
    liquidityDollars: 1100,
    fractionalTradingEnabled: true,
    rawRulesPrimary: "Market settles according to the official high temperature reported for the listed station.",
    rawRulesSecondary: "Temperature settlement source and observation window are defined by the contract terms.",
    parseStatus: "verified",
    parseWarnings: []
  },
  {
    marketTicker: "KXRAINNY-26JUN25",
    eventTicker: "KXRAINNY-26JUN25",
    seriesTicker: "KXRAINNY",
    rawTitle: "Will it rain in New York, NY on Jun 25, 2026?",
    rawSubtitle: "Unsupported rainfall market",
    yesSubtitle: "Yes",
    noSubtitle: "No",
    marketType: "unsupported",
    direction: "unknown",
    cityName: "New York",
    stateCode: "NY",
    eventDateLocal: "2026-06-25",
    eventHourLocal: null,
    timezone: "America/New_York",
    rangeLowerF: null,
    rangeUpperF: null,
    lowerInclusive: false,
    upperInclusive: false,
    stationId: null,
    stationName: null,
    stationLatitude: null,
    stationLongitude: null,
    settlementSourceName: null,
    settlementSourceUrl: null,
    contractUrl: "https://kalshi.com",
    contractTermsUrl: "https://kalshi.com",
    closeTime: "2026-06-25T20:00:00Z",
    expirationTime: null,
    yesBid: 0.5,
    yesAsk: 0.55,
    noBid: 0.45,
    noAsk: 0.5,
    lastPrice: 0.52,
    volume: 100,
    volume24h: 20,
    openInterest: 100,
    liquidityDollars: 100,
    fractionalTradingEnabled: false,
    rawRulesPrimary: null,
    rawRulesSecondary: null,
    parseStatus: "unsupported",
    parseWarnings: ["No estimate available — settlement terms or station mapping could not be verified."]
  }
];

export const fixtureOrderBooks: Record<string, OrderBook> = {
  "KXHIGHNY-26JUN25-B75": {
    yesBids: [{ price: 0.55, quantity: 300 }],
    noBids: [{ price: 0.42, quantity: 220 }]
  },
  "KXHIGHAUS-26JUN25-B100": {
    yesBids: [{ price: 0.28, quantity: 260 }],
    noBids: [{ price: 0.69, quantity: 200 }]
  }
};

export const fixtureProbabilities: Record<string, MarketProbability> = {
  "KXHIGHNY-26JUN25-B75": {
    marketTicker: "KXHIGHNY-26JUN25-B75",
    yesProbability: 0.69,
    noProbability: 0.31,
    meanTemperatureF: 78.6,
    medianTemperatureF: 78.4,
    p10TemperatureF: 75.9,
    p25TemperatureF: 77.2,
    p75TemperatureF: 80.1,
    p90TemperatureF: 81.5,
    confidence: "medium",
    uncertaintyF: 2.1,
    modelInputs: { nbmWeight: 0.45, hrrrWeight: 0.35, nwsWeight: 0.2, observationsWeight: 0 },
    reasons: ["NBM and NWS paths are above the contract threshold.", "Order-book depth supports the displayed size."],
    warnings: ["Demo data — not live market or forecast information."],
    sourceLinks: [
      { label: "Kalshi markets", url: "https://kalshi.com/markets", sourceType: "kalshi", whyItMatters: "Kalshi rules: settlement definition" },
      { label: "NOAA NBM source", url: "https://noaa-nbm-grib2-pds.s3.amazonaws.com", sourceType: "nbm", whyItMatters: "NBM: blended NOAA forecast baseline" },
      { label: "NOAA HRRR source", url: "https://noaa-hrrr-bdp-pds.s3.amazonaws.com", sourceType: "hrrr", whyItMatters: "HRRR: high-resolution short-term forecast" },
      { label: "NWS hourly forecast", url: "https://api.weather.gov", sourceType: "nws", whyItMatters: "NWS: official forecast context" },
      { label: "METAR observations", url: "https://aviationweather.gov/api/data/metar?ids=KNYC", sourceType: "metar", whyItMatters: "METAR: current station observation" }
    ],
    simulation: { temperaturesF: [74, 76, 77, 78, 79, 81, 82, 75, 80, 78] }
  },
  "KXHIGHAUS-26JUN25-B100": {
    marketTicker: "KXHIGHAUS-26JUN25-B100",
    yesProbability: 0.38,
    noProbability: 0.62,
    meanTemperatureF: 98.8,
    medianTemperatureF: 98.6,
    p10TemperatureF: 96.2,
    p25TemperatureF: 97.4,
    p75TemperatureF: 100.3,
    p90TemperatureF: 101.7,
    confidence: "medium",
    uncertaintyF: 2.4,
    modelInputs: { nbmWeight: 0.45, hrrrWeight: 0.35, nwsWeight: 0.2, observationsWeight: 0 },
    reasons: ["Distribution leaves meaningful right-tail heat risk.", "No side currently has enough post-buffer edge for a large position."],
    warnings: ["Demo data — not live market or forecast information."],
    sourceLinks: [
      { label: "Kalshi markets", url: "https://kalshi.com/markets", sourceType: "kalshi", whyItMatters: "Kalshi rules: settlement definition" },
      { label: "NOAA NBM source", url: "https://noaa-nbm-grib2-pds.s3.amazonaws.com", sourceType: "nbm", whyItMatters: "NBM: blended NOAA forecast baseline" },
      { label: "NOAA HRRR source", url: "https://noaa-hrrr-bdp-pds.s3.amazonaws.com", sourceType: "hrrr", whyItMatters: "HRRR: high-resolution short-term forecast" },
      { label: "NWS hourly forecast", url: "https://api.weather.gov", sourceType: "nws", whyItMatters: "NWS: official forecast context" },
      { label: "METAR observations", url: "https://aviationweather.gov/api/data/metar?ids=KAUS", sourceType: "metar", whyItMatters: "METAR: current station observation" }
    ],
    simulation: { temperaturesF: [96, 97, 99, 100, 101, 98, 97, 102, 99, 100] }
  }
};
